Repository youki-dev/youki, pull requests merged in 2023-10, with the labels that each got.

#2370 Feat/podman rootless
  .github/workflows/e2e.yaml
  .github/workflows/main.yml
  .github/workflows/podman_tests.yaml
  Cargo.lock
  MirgationGuide.md
  README.md
  crates/libcgroups/Cargo.toml
  crates/libcgroups/src/common.rs
  crates/libcgroups/src/stub/systemd/manager.rs
  crates/libcgroups/src/systemd/controller.rs
  crates/libcgroups/src/systemd/cpu.rs
  crates/libcgroups/src/systemd/cpuset.rs
  crates/libcgroups/src/systemd/dbus/client.rs
  crates/libcgroups/src/systemd/dbus/mod.rs
  crates/libcgroups/src/systemd/dbus/systemd_api.rs
  crates/libcgroups/src/systemd/dbus_native/client.rs
  crates/libcgroups/src/systemd/dbus_native/dbus.rs
  crates/libcgroups/src/systemd/dbus_native/message.rs
  crates/libcgroups/src/systemd/dbus_native/mod.rs
  crates/libcgroups/src/systemd/dbus_native/proxy.rs
  crates/libcgroups/src/systemd/dbus_native/serialize.rs
  crates/libcgroups/src/systemd/dbus_native/utils.rs
  crates/libcgroups/src/systemd/manager.rs
  crates/libcgroups/src/systemd/memory.rs
  crates/libcgroups/src/systemd/mod.rs
  crates/libcgroups/src/systemd/pids.rs
  crates/libcgroups/src/systemd/unified.rs
  crates/libcontainer/README.md
  crates/libcontainer/src/process/container_main_process.rs
  docs/src/developer/libcgroups.md
  docs/src/user/basic_setup.md
  docs/src/user/libcgroups.md
  justfile
Labels: kind/feature

#2406 Add initial tests for rootless podman
  .github/workflows/e2e.yaml
  justfile
  tests/rootless-tests/run.sh
Labels: kind/test

#2369 update nix to 0.27.1
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcgroups/src/systemd/dbus_native/dbus.rs
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/channel.rs
  crates/libcontainer/src/process/fork.rs
  crates/libcontainer/src/process/seccomp_listener.rs
  crates/libcontainer/src/syscall/linux.rs
  crates/libcontainer/src/tty.rs
  crates/libcontainer/src/utils.rs
  crates/youki/Cargo.toml
  tests/rust-integration-tests/integration_test/Cargo.toml
  tests/rust-integration-tests/integration_test/src/tests/seccomp_notify/seccomp_agent.rs
  tests/rust-integration-tests/runtimetest/Cargo.toml
Labels: kind/cleanup

#2420 Use static build of wasmedge
  crates/youki/Cargo.toml
  docs/src/user/webassembly.md
  justfile
Labels: kind/cleanup

#2411 feat: allow customize cgroup root path
  crates/libcgroups/src/common.rs
Labels: kind/feature

#2425 Use raw syscalls to avoid sporadic hangs
  crates/libcontainer/src/syscall/linux.rs
Labels: kind/bug

#2434 docs: update docs regarding the changes in #2411
  docs/src/developer/libcgroups.md
  docs/src/user/libcgroups.md
Labels: kind/documentation

#2438 Fix device duplication in rootfs preparation
  crates/libcontainer/src/rootfs/rootfs.rs
Labels: kind/bug

#2437 v0.3.0
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/liboci-cli/Cargo.toml
  crates/youki/Cargo.toml
  docs/src/user/basic_setup.md
  justfile
Labels: kind/cleanup
