Repository youki-dev/youki, pull requests merged in 2023-09, with the labels that each got.

#2334 Update Migration Guide for 0.2.0 release
  MirgationGuide.md
Labels: kind/cleanup

#2333 v0.2.0
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/liboci-cli/Cargo.toml
  crates/youki/Cargo.toml
  docs/src/user/basic_setup.md
Labels: kind/feature

#2279 Change rootless required function and privilege decision
  crates/libcgroups/src/common.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/error.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/user_ns.rs
  crates/libcontainer/src/utils.rs
  crates/youki/src/observability.rs
  crates/youki/src/rootpath.rs
Labels: kind/cleanup

#2365 Skip the tests related to criu when criu is not found
  tests/rust-integration-tests/integration_test/src/tests/lifecycle/container_lifecycle.rs
  tests/rust-integration-tests/integration_test/src/tests/lifecycle/util.rs
Labels: kind/test

#2330 Refactor doc test and justfile
  .github/workflows/e2e.yaml
  .github/workflows/main.yml
  .github/workflows/release.yml
  README.md
  justfile
Labels: kind/cleanup

#2382 Add the documentation for debugging
  docs/src/SUMMARY.md
  docs/src/developer/debugging.md
Labels: kind/documentation

#2381 Update the developer documentation for the e2e tests.
  docs/src/SUMMARY.md
  docs/src/assets/rust_oci_tests.png
  docs/src/developer/containerd_integration_test_using_youki.md
  docs/src/developer/debugging.md
  docs/src/developer/e2e/containerd_integration_test_using_youki.md
  docs/src/developer/e2e/e2e_tests.md
  docs/src/developer/e2e/integration_test.md
  docs/src/developer/e2e/runtime_tools.md
  docs/src/developer/e2e/runtimetest.md
  docs/src/developer/e2e/rust_oci_test.md
  docs/src/developer/e2e/test_framework.md
  tests/rust-integration-tests/integration_test/src/main.rs
  tests/rust-integration-tests/integration_test/src/tests/example/hello_world.rs
  tests/rust-integration-tests/integration_test/src/tests/example/mod.rs
  tests/rust-integration-tests/integration_test/src/tests/mod.rs
  tests/rust-integration-tests/runtimetest/src/main.rs
  tests/rust-integration-tests/runtimetest/src/tests.rs
Labels: kind/documentation
