Repository youki-dev/youki, pull requests merged in 2023-07, with the labels that each got.

#2143 Increate musl CI test timeout to 20
  .github/workflows/main.yml
Labels: kind/miscellaneous

#2122 Add one label to generate release notes
  .github/release.yml
  .github/workflows/label.yaml
Labels: kind/documentation

#2150 disable musl test for now
  .github/workflows/main.yml
Labels: kind/test

#2158 Fix musl test function not parametered correctly
  scripts/musl_test.sh
Labels: kind/test

#2149 Liboci additional flags and subcommands, as required by ociplex
  crates/liboci-cli/README.md
  crates/liboci-cli/src/checkpoint.rs
  crates/liboci-cli/src/create.rs
  crates/liboci-cli/src/exec.rs
  crates/liboci-cli/src/features.rs
  crates/liboci-cli/src/lib.rs
  crates/liboci-cli/src/list.rs
  crates/liboci-cli/src/run.rs
  crates/liboci-cli/src/spec.rs
  crates/liboci-cli/src/update.rs
  crates/youki/src/commands/features.rs
  crates/youki/src/commands/mod.rs
  crates/youki/src/main.rs
Labels: kind/feature

#2155 Use syscall type to delay the creation of syscall struct.
  crates/libcontainer/src/container/builder.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/container_delete.rs
  crates/libcontainer/src/container/container_events.rs
  crates/libcontainer/src/container/container_kill.rs
  crates/libcontainer/src/container/container_pause.rs
  crates/libcontainer/src/container/container_resume.rs
  crates/libcontainer/src/container/container_start.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/process/args.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_intermediate_process.rs
  crates/libcontainer/src/syscall/syscall.rs
  crates/youki/src/commands/create.rs
  crates/youki/src/commands/exec.rs
  crates/youki/src/commands/run.rs
Labels: kind/cleanup, breaking change

#2164 add io priority
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/error.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/syscall/linux.rs
  crates/libcontainer/src/syscall/syscall.rs
  crates/libcontainer/src/syscall/test.rs
Labels: kind/feature

#2168 Refactor the libcgroups interface
  crates/libcgroups/src/common.rs
  crates/libcgroups/src/systemd/manager.rs
  crates/libcgroups/src/v1/manager.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/container_delete.rs
  crates/libcontainer/src/container/container_events.rs
  crates/libcontainer/src/container/container_kill.rs
  crates/libcontainer/src/container/container_pause.rs
  crates/libcontainer/src/container/container_resume.rs
  crates/libcontainer/src/notify_socket.rs
  crates/libcontainer/src/process/args.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_intermediate_process.rs
  crates/youki/src/commands/mod.rs
Labels: kind/cleanup, breaking change

#2186 refactored executor and executor manager
  crates/libcontainer/src/container/builder.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/process/args.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/workload/default.rs
  crates/libcontainer/src/workload/mod.rs
  crates/youki/src/commands/create.rs
  crates/youki/src/commands/exec.rs
  crates/youki/src/commands/run.rs
  crates/youki/src/workload/executor.rs
  crates/youki/src/workload/wasmedge.rs
  crates/youki/src/workload/wasmer.rs
  crates/youki/src/workload/wasmtime.rs
  docs/src/developer/libcontainer.md
Labels: kind/cleanup, breaking change

#2193 Make container_args clone-able
  crates/libcontainer/src/channel.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/process/args.rs
  crates/libcontainer/src/process/channel.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_main_process.rs
  crates/libcontainer/src/process/message.rs
  crates/libcontainer/src/rootless.rs
Labels: kind/cleanup
