Repository youki-dev/youki, pull requests merged in 2023-11, with the labels that each got.

#2496 Grouping patch updates in dependabot.
  .github/dependabot.yml
Labels: kind/cleanup

#2497 Specify the protobuf crate because of the rust-criu crate
  Cargo.lock
  crates/libcontainer/Cargo.toml
Labels: kind/bug

#2502 Fix the config of the dependenda bot
  .github/dependabot.yml
Labels: kind/cleanup

#2503 feature(main): add release strip
  .cargo/config.toml
Labels: kind/cleanup

#2525 docs(libcgroup): add docs for several items in 'libcgroup::v2'
  crates/libcgroups/src/v2/manager.rs
  crates/libcgroups/src/v2/util.rs
Labels: kind/cleanup

#2524 fix(libcgroups): report CPU throttling stats in 'libcgroups::v2'
  crates/libcgroups/src/v2/cpu.rs
Labels: kind/feature

#2531 test(integration_test): port 'runtime-tools/validation/linux_seccomp'
  tests/integration_test/src/main.rs
  tests/integration_test/src/tests/mod.rs
  tests/integration_test/src/tests/seccomp/mod.rs
  tests/runtimetest/src/main.rs
  tests/runtimetest/src/tests.rs
Labels: kind/test

#2530 fix(libcgroups): clean up 'libcgroups::v1::manager'
  crates/libcgroups/src/v1/manager.rs
Labels: kind/cleanup

#2498 fix(main): support arm64 release youki
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  Cross.toml
  cross/Dockerfile.gnu
  justfile
  scripts/build.sh
Labels: kind/feature

#2535 small typo in trace message
  crates/libcontainer/src/user_ns.rs
Labels: kind/cleanup

#2510 docs(main): support arm64 release docs
  .github/workflows/release.yml
  .gitignore
  crates/libcontainer/Cargo.toml
  crates/youki/Cargo.toml
  docs/src/user/basic_setup.md
  justfile
  scripts/release_tag.sh
Labels: kind/documentation
