Repository youki-dev/youki, pull requests merged in 2023-12, with the labels that each got.

#2550 fix docs
  docs/src/developer/e2e/rust_oci_test.md
Labels: kind/documentation

#2548 Set up userns in a straightforward way
  .github/workflows/e2e.yaml
  .github/workflows/main.yml
  crates/libcontainer/src/process/container_intermediate_process.rs
Labels: kind/cleanup

#2557 Rust 1.74.1
  crates/libcgroups/src/v1/blkio.rs
  crates/libcontainer/src/signal.rs
  rust-toolchain.toml
Labels: kind/cleanup

#2541 Simplify release workflow
  .github/workflows/release.yml
  scripts/release_tag.sh
Labels: kind/cleanup

#2537 docs(main): auto release node using just
  .github/workflows/release.yaml
  .github/workflows/tagpr.yaml
  .github/workflows/update_version_config.yaml
  .tagpr
  justfile
Labels: kind/documentation

#2572 Ignore CHANGELOG.md in typos
  .typos.toml
Labels: kind/cleanup

#2573 docs(main): auto release node using just
  .tagpr
Labels: kind/bug

#2532 Fix emulated cgroups v1 subsystem when running docker-in-docker
  crates/libcontainer/src/rootfs/mount.rs
  crates/youki/src/observability.rs
Labels: kind/bug

#2536 (feat) add support for `musl` using `cross-rs`
  .github/workflows/e2e.yaml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  Cross.toml
  crates/libcgroups/src/v2/devices/mocks.rs
  cross/Dockerfile.gnu
  cross/Dockerfile.musl
  justfile
  scripts/build.sh
  scripts/cargo.sh
  scripts/clean.sh
  scripts/features_test.sh
  scripts/musl_test.sh
Labels: kind/feature

#2583 New Releases needs approval from the maintainer
  .github/workflows/release.yaml
Labels: kind/cleanup

#2585 fix: just instead make
  docs/src/user/basic_setup.md
Labels: kind/documentation
