Repository youki-dev/youki, pull requests merged in 2024-09, with the labels that each got.

#2897 prepare for version 0.4.1
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/liboci-cli/Cargo.toml
  crates/youki/Cargo.toml
  docs/src/user/basic_setup.md
Labels: kind/cleanup

#2904 Update Cargo.toml for v0.4.1
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/liboci-cli/Cargo.toml
  crates/youki/Cargo.toml
  docs/src/user/basic_setup.md
Labels: kind/cleanup

#2900 selinux: create Vagrantfile for SELinux
  experiment/selinux/README.md
  experiment/selinux/Vagrantfile
  experiment/selinux/src/main.rs
  experiment/selinux/src/tools/xattr.rs
Labels: kind/experimental

#2918 ci: update action versions to fix deprecation warnings
  .github/workflows/basic.yml
  .github/workflows/benchmark_execution_time.yml
  .github/workflows/docs.yaml
  .github/workflows/e2e.yaml
  .github/workflows/integration_tests_validation.yaml
  .github/workflows/podman_tests.yaml
  .github/workflows/release.yaml
  .github/workflows/tagpr.yaml
  .github/workflows/update_version_config.yaml
Labels: kind/cleanup

#2928 deps: update wasmedge to 0.14.0
  Cargo.lock
  crates/youki/Cargo.toml
  crates/youki/src/workload/wasmedge.rs
Labels: kind/cleanup

#2921 Cargo.toml: remove unused dependnecies
  Cargo.lock
  crates/libcontainer/Cargo.toml
  crates/youki/Cargo.toml
  tests/contest/contest/Cargo.toml
Labels: dependencies

#2929 deps: update wasmtime
  Cargo.lock
  crates/youki/Cargo.toml
Labels: dependencies

#2934 Bump oci-spec to 0.7.0
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/seccomp/mod.rs
  tests/contest/contest/Cargo.toml
  tests/contest/runtimetest/Cargo.toml
Labels: kind/cleanup

#2936 selinux: fix xattr and remove anyhow
  experiment/selinux/Cargo.lock
  experiment/selinux/Cargo.toml
  experiment/selinux/src/main.rs
  experiment/selinux/src/selinux.rs
  experiment/selinux/src/tools/xattr.rs
Labels: kind/experimental

#2915 Fixed ENAMETOOLONG error in setup_console_socket
  crates/libcontainer/src/tty.rs
Labels: kind/bug
