Repository youki-dev/youki, pull requests merged in 2024-12, with the labels that each got.

#3012 Add option to spawn processes as siblings
  Cargo.lock
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/process/args.rs
  crates/libcontainer/src/process/container_main_process.rs
  crates/libcontainer/tests/as_sibling.rs
Labels: kind/feature

#3019 fix duplicate gids in container creation
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/syscall/test.rs
  tests/contest/contest/src/tests/process_user/process_user_test.rs
Labels: kind/bug

#3023 switch from license-file to license
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/liboci-cli/Cargo.toml
  crates/youki/Cargo.toml
  experiment/seccomp/Cargo.toml
  experiment/selinux/Cargo.toml
Labels: kind/documentation

#2893 Fix --preserve-fds, eliminate stray FD being passed into container
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_main_process.rs
  crates/libcontainer/src/syscall/linux.rs
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/fd_control/mod.rs
  tests/contest/contest/src/tests/lifecycle/container_create.rs
  tests/contest/contest/src/tests/lifecycle/container_lifecycle.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/pidfile/pidfile_test.rs
  tests/contest/contest/src/utils/mod.rs
  tests/contest/contest/src/utils/test_utils.rs
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
  tests/contest/test_framework/src/test_group.rs
  tests/contest/test_framework/src/test_manager.rs
  tests/contest/test_framework/src/testable.rs
Labels: kind/bug

#3016 Prepare for v0.5.0
  .tagpr
  justfile
Labels: kind/cleanup
