Repository youki-dev/youki, pull requests merged in 2024-05, with the labels that each got.

#2779 Update rust version to 1.77.2
  rust-toolchain.toml
Labels: kind/cleanup

#2775 seccomp: Add a case for checking arguments
  experiment/seccomp/Cargo.lock
  experiment/seccomp/Cargo.toml
  experiment/seccomp/src/main.rs
  experiment/seccomp/src/seccomp.rs
Labels: kind/experimental

#2781 deps: Disable unused/unnecessary regex features in libcontainer
  crates/libcontainer/Cargo.toml
Labels: kind/cleanup

#2780 Remove unnecessary chdir
  Vagrantfile.containerd2youki
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/container_delete.rs
  crates/libcontainer/src/container/container_start.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/hooks.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/tty.rs
  justfile
Labels: kind/bug

#2789 Update the release workflow
  .github/workflows/release.yaml
Labels: kind/cleanup

#2794 Release v0.3.3
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/liboci-cli/Cargo.toml
  crates/youki/Cargo.toml
  docs/src/user/basic_setup.md
Labels: kind/cleanup

#2728 Update nix to 0.28.0
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcgroups/src/v1/memory.rs
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/process/container_intermediate_process.rs
  crates/libcontainer/src/process/fork.rs
  crates/libcontainer/src/seccomp/mod.rs
  crates/libcontainer/src/syscall/linux.rs
  crates/youki/Cargo.toml
  tests/contest/contest/Cargo.toml
  tests/contest/contest/src/tests/seccomp_notify/seccomp_agent.rs
  tests/contest/runtimetest/Cargo.toml
  tests/contest/runtimetest/src/tests.rs
Labels: kind/cleanup
