Repository youki-dev/youki, pull requests merged in 2024-07, with the labels that each got.

#2839 Fix typos and bump version for typos ci
  .github/workflows/basic.yml
  .typos.toml
  crates/libcgroups/src/v1/network_priority.rs
  crates/libcgroups/src/v2/memory.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/tty.rs
  docs/src/community/governance.md
  docs/src/developer/e2e/test_framework.md
  tests/contest/runtimetest/src/tests.rs
Labels: kind/cleanup

#2834 docs: fix `with_executor` method description
  crates/libcontainer/src/container/builder.rs
Labels: kind/documentation

#2845 Install nightly for running linter inside devcontainer
  .devcontainer/Dockerfile
Labels: kind/cleanup

#2825 selinux: write xattr related codes.
  experiment/selinux/Cargo.lock
  experiment/selinux/Cargo.toml
  experiment/selinux/src/lib.rs
  experiment/selinux/src/selinux.rs
  experiment/selinux/src/xattr/xattr.rs
  experiment/selinux/src/xattrs/mod.rs
  experiment/selinux/src/xattrs/xattr.rs
Labels: kind/experimental

#2838 Fix/dbus call issue
  crates/libcgroups/src/systemd/dbus_native/dbus.rs
  crates/libcgroups/src/systemd/dbus_native/message.rs
  crates/libcgroups/src/systemd/dbus_native/proxy.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/process/channel.rs
  crates/libcontainer/src/process/container_main_process.rs
  crates/libcontainer/src/process/message.rs
Labels: kind/bug

#2829 Add issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQ.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: kind/cleanup

#2847 chore(deps): update oci-spec to v0.6.7
  Cargo.lock
  crates/libcgroups/src/v1/devices.rs
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/syscall/linux.rs
  crates/libcontainer/src/syscall/syscall.rs
  crates/libcontainer/src/syscall/test.rs
Labels: kind/cleanup

#2854 Bump oci-spec
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  tests/contest/runtimetest/Cargo.toml
Labels: kind/cleanup

#2857 Update devcontainer.json
  .devcontainer/devcontainer.json
Labels: kind/cleanup

#2856 Apply building best practices to `.devcontainer/Dockerfile`
  .devcontainer/Dockerfile
Labels: kind/cleanup

#2855 Fix markdown format in experiment/selinux/README.md
  experiment/selinux/README.md
Labels: kind/cleanup

#2809 initial progress on supporting OwnedFd
  crates/libcontainer/src/channel.rs
  crates/libcontainer/src/process/channel.rs
  crates/libcontainer/src/process/container_intermediate_process.rs
  crates/libcontainer/src/process/container_main_process.rs
  crates/libcontainer/src/process/fork.rs
Labels: kind/cleanup
