Repository youki-dev/youki, pull requests merged in 2024-04, with the labels that each got.

#2729 Init a seccomp project
  .github/workflows/label.yaml
  Cargo.toml
  experiment/seccomp/Cargo.lock
  experiment/seccomp/Cargo.toml
  experiment/seccomp/README.md
  experiment/seccomp/src/instruction/arch.rs
  experiment/seccomp/src/instruction/consts.rs
  experiment/seccomp/src/instruction/inst.rs
  experiment/seccomp/src/instruction/mod.rs
  experiment/seccomp/src/lib.rs
  experiment/seccomp/src/main.rs
  experiment/seccomp/src/seccomp.rs
Labels: kind/experimental

#2719 Add support for rsvd hugetlb cgroup
  crates/libcgroups/src/v1/hugetlb.rs
  crates/libcgroups/src/v2/hugetlb.rs
  tests/contest/contest/src/tests/tlb/tlb_test.rs
Labels: kind/feature

#2746 Rust 1.77.1
  crates/libcgroups/src/common.rs
  crates/libcgroups/src/lib.rs
  crates/libcgroups/src/systemd/dbus_native/dbus.rs
  crates/libcgroups/src/systemd/dbus_native/proxy.rs
  crates/libcontainer/src/process/intel_rdt.rs
  crates/libcontainer/src/process/seccomp_listener.rs
  crates/libcontainer/src/rootfs/mount.rs
  rust-toolchain.toml
  tests/contest/contest/src/tests/cgroups/network.rs
  tests/contest/contest/src/utils/mod.rs
  tests/contest/runtimetest/src/utils.rs
Labels: kind/cleanup

#2753 Make our codespaces more useful
  .devcontainer/Dockerfile
  README.md
  experiment/seccomp/rust-toolchain.toml
Labels: kind/cleanup

#2759 Fix README.md
  README.md
Labels: kind/cleanup

#2752 update wasmtime dep to 19.0.1, replace wasmtime-wasi with wasi-common
  Cargo.lock
  crates/youki/Cargo.toml
  crates/youki/src/workload/wasmtime.rs
Labels: kind/cleanup

#2764 Reset console sockets to original in setup_console test
  crates/libcontainer/src/tty.rs
Labels: kind/cleanup

#2763 seccomp: Use offset_of!
  experiment/seccomp/src/instruction/arch.rs
  experiment/seccomp/src/instruction/consts.rs
Labels: kind/experimental

#2720 Fix cgroups determination in exec implementation
  Cross.toml
  crates/libcgroups/src/systemd/dbus_native/client.rs
  crates/libcgroups/src/systemd/dbus_native/dbus.rs
  crates/libcgroups/src/systemd/dbus_native/proxy.rs
  crates/libcgroups/src/systemd/manager.rs
  crates/libcgroups/src/v2/manager.rs
  crates/libcontainer/src/config.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/container.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/utils.rs
  cross/Dockerfile.gnu
  cross/Dockerfile.musl
  hack/busctl.sh
  scripts/cargo.sh
  tests/rootless-tests/run.sh
Labels: kind/bug
