Repository youki-dev/youki, pull requests merged in 2024-01, with the labels that each got.

#2558 Updaet to Containerd 1.7.11
  .github/workflows/e2e.yaml
  Vagrantfile.containerd2youki
Labels: kind/cleanup

#2608 chore(deps) bump tabwriter, windows-core, tempfile, memchr, clang-sys
  Cargo.lock
Labels: kind/cleanup

#2621 [doc] Update doc with `cross-rs` and `musl` builds
  docs/src/user/basic_setup.md
  scripts/build.sh
  scripts/release_tag.sh
Labels: kind/documentation

#2629 Fix the missed naming changes in integration test validation CI
  .github/workflows/integration_tests_validation.yaml
  docs/src/developer/e2e/rust_oci_test.md
  justfile
Labels: kind/cleanup

#2638 Roll up various minor and major version dep upgrade
  Cargo.lock
  crates/youki/Cargo.toml
Labels: kind/cleanup

#2645 Add docker-in-docker e2e test
  .github/workflows/e2e.yaml
  justfile
  tests/dind/daemon.json
  tests/dind/run.sh
Labels: kind/test

#2495 add schedule entity
  Cargo.lock
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/error.rs
  crates/libcontainer/src/process/container_init_process.rs
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/scheduler/mod.rs
  tests/contest/contest/src/tests/scheduler/scheduler_policy.rs
  tests/contest/runtimetest/Cargo.toml
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/feature

#1544 Add domainname test
  Cargo.lock
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/domainname/mod.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/runtimetest/Cargo.toml
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/test

#2647 Re enable skipped e2e tests
  justfile
  scripts/contest.sh
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/domainname/mod.rs
  tests/contest/contest/src/tests/scheduler/scheduler_policy.rs
  tests/contest/contest/src/utils/mod.rs
  tests/contest/contest/src/utils/support.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/test

#2663 Address GHSA-xr7r-f8xq-vfvv
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_main_process.rs
Labels: kind/feature
