Repository youki-dev/youki, pull requests merged in 2024-10, with the labels that each got.

#2940 remove incorrect dependency in readme
  README.md
Labels: kind/cleanup

#2941 .github/workflows/basic: check unused deps on 'check' job
  .github/workflows/basic.yml
Labels: dependencies

#2924 Add seccomp into feature flags of youki to be compiled in
  crates/youki/Cargo.toml
  scripts/features_test.sh
Labels: kind/cleanup

#2947 Add the affiliations of youki maintainers
  docs/src/community/maintainer.md
Labels: kind/documentation

#2946 seccomp: Update experiment seccomp program
  experiment/seccomp/Cargo.lock
  experiment/seccomp/Cargo.toml
  experiment/seccomp/src/instruction/arch.rs
  experiment/seccomp/src/main.rs
  experiment/seccomp/src/seccomp.rs
Labels: kind/experimental

#2964 print "unknown" instead of defaults if we cannot get kernel config
  crates/youki/src/commands/info.rs
Labels: kind/cleanup

#2923 fix(libcontainer) no_pivot args is not used
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/init_builder.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/process/args.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/syscall/linux.rs
  crates/libcontainer/src/syscall/syscall.rs
  crates/libcontainer/src/syscall/test.rs
  crates/youki/src/commands/create.rs
  crates/youki/src/commands/run.rs
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/no_pivot/mod.rs
  tests/contest/contest/src/utils/test_utils.rs
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/bug
