Repository youki-dev/youki, pull requests merged in 2024-02, with the labels that each got.

#2667 Rollup dep updates
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/youki/Cargo.toml
Labels: kind/cleanup

#2674 Rollup dep update
  Cargo.lock
Labels: dependencies

#2677 Fill in TODO
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_main_process.rs
Labels: kind/cleanup

#2680 Fix the links of contest
  docs/src/developer/e2e/rust_oci_test.md
Labels: kind/cleanup

#2685 Set '--test-threads' option to 1 in unit tests
  justfile
Labels: kind/test

#2646 add io priority e2e test
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/io_priority/io_priority_test.rs
  tests/contest/contest/src/tests/io_priority/mod.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/test

#2687 (fix) podman e2e : Update workflow for new required deps, add vagrantfile
  .github/workflows/podman_tests.yaml
  Vagrantfile.podmane2e
Labels: kind/test

#2699 Add missed test-threads=1 to coverage CI
  .github/workflows/basic.yml
  scripts/features_test.sh
Labels: kind/cleanup

#2707 Fix integration test validation CI, make io_priority test conditional
  .github/workflows/integration_tests_validation.yaml
  tests/contest/contest/src/tests/io_priority/io_priority_test.rs
Labels: kind/test

#2705 Improve error reporting and logging
  crates/libcgroups/src/common.rs
  crates/libcgroups/src/stats.rs
  crates/libcgroups/src/systemd/dbus_native/dbus.rs
  crates/libcgroups/src/systemd/dbus_native/message.rs
  crates/libcgroups/src/systemd/dbus_native/utils.rs
  crates/libcgroups/src/v1/manager.rs
  crates/libcgroups/src/v2/io.rs
  crates/libcontainer/src/container/builder_impl.rs
  crates/libcontainer/src/container/container_checkpoint.rs
  crates/libcontainer/src/container/container_kill.rs
  crates/libcontainer/src/container/mod.rs
  crates/libcontainer/src/container/tenant_builder.rs
  crates/libcontainer/src/error.rs
  crates/libcontainer/src/notify_socket.rs
  crates/libcontainer/src/process/channel.rs
  crates/libcontainer/src/process/container_init_process.rs
  crates/libcontainer/src/process/container_intermediate_process.rs
  crates/libcontainer/src/process/intel_rdt.rs
  crates/libcontainer/src/user_ns.rs
  crates/libcontainer/src/utils.rs
  crates/libcontainer/src/workload/default.rs
  crates/libcontainer/src/workload/mod.rs
  crates/youki/src/main.rs
  crates/youki/src/rootpath.rs
  crates/youki/src/workload/wasmedge.rs
Labels: kind/cleanup, breaking change
