Repository youki-dev/youki, pull requests merged in 2025-06, with the labels that each got.

#3161 Add uid_mappings test
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/uid_mappings/mod.rs
  tests/contest/contest/src/tests/uid_mappings/uid_mappings_test.rs
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/test

#3172 fix: update devcontainer.json
  .devcontainer/devcontainer.json
Labels: kind/cleanup

#3042 Remove oci tests that are duplicates of contest
  scripts/oci_integration_tests.sh
Labels: kind/test

#3184 Remove oci tests that are duplicates of contest
  scripts/oci_integration_tests.sh
Labels: kind/test

#3180 fix: Ignoring CPU realtime on cgroupsv2 if set to zero
  crates/libcgroups/src/systemd/cpu.rs
  crates/libcgroups/src/v2/cpu.rs
Labels: kind/bug

#3159 fix: protobuf bug on docs rs
  Cargo.lock
  crates/libcontainer/Cargo.toml
Labels: kind/documentation

#3175 docs: clarify reviewer qualification and self-nomination process
  docs/src/community/governance.md
Labels: kind/documentation
