Repository youki-dev/youki, pull requests merged in 2025-04, with the labels that each got.

#3085 update rust version to 1.85.0
  .github/workflows/basic.yml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  crates/libcgroups/src/v1/devices.rs
  crates/libcontainer/src/config.rs
  crates/libcontainer/src/process/channel.rs
  crates/libcontainer/src/process/container_init_process.rs
  rust-toolchain.toml
  tests/contest/contest/src/utils/test_utils.rs
Labels: kind/cleanup

#3024 add-test-linux_rootfs_propagation
  Cargo.lock
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/rootfs_propagation/mod.rs
  tests/contest/contest/src/tests/rootfs_propagation/rootfs_propagation_test.rs
  tests/contest/runtimetest/Cargo.toml
  tests/contest/runtimetest/src/main.rs
  tests/contest/runtimetest/src/tests.rs
Labels: kind/test

#3129 chore(docs): Fix codecov link in README
  README.md
Labels: kind/documentation

#2986 Add a relative_network_cgroups test as one of the integration tests
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/cgroups/network/absolute_network.rs
  tests/contest/contest/src/tests/cgroups/network/mod.rs
  tests/contest/contest/src/tests/cgroups/network/relative_network.rs
Labels: kind/test

#3131 use additional gids,user,group in exec, inject path iif not given
  crates/libcontainer/src/container/tenant_builder.rs
  crates/youki/src/commands/exec.rs
Labels: kind/bug

#3154 Bump oci-spec.rs to v0.8.1
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/youki/src/commands/features.rs
  tests/contest/contest/Cargo.toml
  tests/contest/runtimetest/Cargo.toml
Labels: dependencies
