Repository youki-dev/youki, pull requests merged in 2025-09, with the labels that each got.

#3249 Unskip runc tests after CI runc update 1.3.1
  tests/contest/contest/src/tests/domainname/mod.rs
  tests/contest/contest/src/tests/exec_cpu_affinity/exec_cpu_affinity_test.rs
  tests/contest/contest/src/tests/io_priority/io_priority_test.rs
  tests/contest/contest/src/tests/process_user/process_user_test.rs
  tests/contest/contest/src/tests/rootfs_propagation/rootfs_propagation_test.rs
  tests/contest/contest/src/tests/scheduler/scheduler_policy.rs
Labels: kind/test

#3246 Update Rust edition requirement in docs to 2024
  README.md
Labels: kind/documentation

#3260 Fix podman ci
  .github/workflows/podman_tests.yaml
Labels: kind/cleanup
