Repository youki-dev/youki, pull requests merged in 2025-03, with the labels that each got.

#3073 lset_file_label should check for symlink instead of raw file
  experiment/selinux/src/selinux_label.rs
Labels: kind/experimental

#3060 Remove problematic comments between package name in apt install
  .devcontainer/Dockerfile
Labels: kind/cleanup

#3082 Add `delete` test
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/delete/delete_test.rs
  tests/contest/contest/src/tests/delete/mod.rs
  tests/contest/contest/src/tests/lifecycle/container_lifecycle.rs
  tests/contest/contest/src/tests/lifecycle/state.rs
  tests/contest/contest/src/tests/mod.rs
Labels: kind/test

#3102 chore(ci): add cgroup v1 compatibility for tests on ubuntu-24.04
  .github/workflows/e2e.yaml
Labels: kind/cleanup

#3106 fix: CPU controller tests for Kernel 6.10 cgroup v2 changes
  tests/contest/contest/src/tests/cgroups/cpu/v2.rs
Labels: kind/test

#3097 chore(ci): Upgrade GitHub Actions workflows for `ubuntu-24.04`
  .github/workflows/basic.yml
  .github/workflows/benchmark_execution_time.yml
  .github/workflows/docs.yaml
  .github/workflows/e2e.yaml
  .github/workflows/integration_tests_validation.yaml
  .github/workflows/podman_tests.yaml
  .github/workflows/release.yaml
  .github/workflows/update_version_config.yaml
Labels: kind/cleanup

#3112 Security: Fix compromised `tj-actions/changed-files` action
  .github/workflows/basic.yml
  .github/workflows/integration_tests_validation.yaml
Labels: kind/bug

#3118 fix: release ci tests also need apparmor disable
  .github/workflows/basic.yml
  .github/workflows/integration_tests_validation.yaml
  .github/workflows/release.yaml
Labels: kind/cleanup

#3120 chore(ci): add criu ppa for podman-tests ci
  .github/workflows/podman_tests.yaml
Labels: kind/cleanup

#3123 bump nix to 0.29.0
  Cargo.lock
  crates/libcgroups/Cargo.toml
  crates/libcontainer/Cargo.toml
  crates/libcontainer/src/channel.rs
  crates/youki/Cargo.toml
  experiment/seccomp/Cargo.lock
  experiment/seccomp/Cargo.toml
  experiment/seccomp/src/main.rs
  tests/contest/contest/Cargo.toml
  tests/contest/contest/src/tests/seccomp_notify/seccomp_agent.rs
  tests/contest/runtimetest/Cargo.toml
Labels: kind/cleanup
