Repository youki-dev/youki, pull requests merged in 2025-01, with the labels that each got.

#3033 Use later stable rust version 1.81.0 to fix the CI
  crates/libcontainer/src/utils.rs
  rust-toolchain.toml
Labels: kind/cleanup

#3036 Don't specify the versionFile for tagpr
  .tagpr
Labels: kind/cleanup

#3039 Do `cargo check` before releasing a new version
  justfile
Labels: kind/cleanup

#3041 Fix building the wasmedge feature
  Cargo.lock
Labels: kind/bug

#3049 Add a PR template file
  .github/pull_request_template.md
Labels: kind/cleanup

#3051 add process rlimits fail test
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/process_rlimits_fail/mod.rs
  tests/contest/contest/src/tests/process_rlimits_fail/process_rlimits_fail_test.rs
Labels: kind/test

#2937 Use MountOption enum to parse mount options defined in the spec
  crates/libcontainer/src/rootfs/utils.rs
  crates/libcontainer/src/syscall/linux.rs
Labels: kind/cleanup
