Repository youki-dev/youki, pull requests merged in 2025-05, with the labels that each got.

#3160 Fixed grammatical error in README
  README.md
Labels: kind/documentation

#2996 add kill test
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/kill/kill_test.rs
  tests/contest/contest/src/tests/kill/mod.rs
  tests/contest/contest/src/tests/lifecycle/container_lifecycle.rs
  tests/contest/contest/src/tests/mod.rs
Labels: kind/test

#3165 allow running selected tests in contest.sh and justfile
  justfile
  scripts/contest.sh
Labels: kind/cleanup

#3150 fix: capet Ambient log level
  crates/libcontainer/src/capabilities.rs
Labels: kind/cleanup

#3010 add test process_capabilities_fail
  tests/contest/contest/src/main.rs
  tests/contest/contest/src/tests/mod.rs
  tests/contest/contest/src/tests/process_capabilities_fail/mod.rs
  tests/contest/contest/src/tests/process_capabilities_fail/process_capabilities_fail_test.rs
  tests/contest/contest/src/utils/test_utils.rs
Labels: kind/test

#3168 fix typos and outdated typos ci action
  .github/workflows/basic.yml
  .typos.toml
  MigrationGuide.md
  tests/contest/contest/src/tests/tlb/tlb_test.rs
Labels: kind/cleanup

#3157 fix: mount retry and logging
  crates/libcontainer/src/rootfs/mount.rs
  crates/libcontainer/src/utils.rs
Labels: kind/bug

#3099 fix: Gracefully terminate processes after successful execution of Wasm executors
  crates/youki/src/workload/wasmedge.rs
  crates/youki/src/workload/wasmer.rs
  crates/youki/src/workload/wasmtime.rs
Labels: kind/bug
