Repository youki-dev/youki, pull requests merged in 2025-08, with the labels that each got.

#3213 chore(justfile):add install recipe
  justfile
Labels: kind/cleanup

#3228 added saku3 as reviewers
  docs/src/community/maintainer.md
Labels: kind/documentation

#3200 fix(3197): fix youki version command Part of Enhancing Compatibility with runc
  crates/youki/src/commands/info.rs
  crates/youki/src/main.rs
Labels: kind/feature, breaking change

#3221 Changed the events_logger in the Dev Container to file
  .devcontainer/Dockerfile
  .devcontainer/devcontainer-lock.json
  .devcontainer/devcontainer.json
Labels: kind/documentation
